name = input("enter your name:")
print("Hello, " + name)
city = input("enter your city:")
print("your city is " + city)
my_fav_language = input("enter your favorite language: ")
print("MY favorite language is " + my_fav_language)
college = input("enter your college name:")
print("MY college name is "+ college)
name = input(str("enter your name:"))
print(name)
age = input(str("enter your age:"))
print(age)
city = input(str("enter your city:"))
print(city)
dream_company = input(str("enter your dream_company:"))
position = input(str(("enter your position:")))
print("I want to work at" + dream_company + "as a " + position)
print("MY BIODATA")
Name = input("enter your Name:")
Age = input("enter your age:")
Branch = input("enter your Branch:")
Cgpa = input("enter your Cgpa:")
City = input("enter your CIty:")
College = input("enter your college:")
print(Name)
print(Branch)
print(Cgpa)
print(City)
print(College)
